name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # adjust this to your main branch 

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: '--openssl-legacy-provider'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git identity
        run: |
          git config --global user.email "kavi.radsar@gmail.com"
          git config --global user.name "radsar"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'  # adjust to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          npm run build
          npm run publishsitemap
          touch docs/.nojekyll

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: docs  # adjust this to your build output directory

      - name: Deploy
        run: npm run deploy
        env:
          CI: true  # Optional: Set CI=true to prevent prompts in some scripts

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: docs  # adjust this to your build output directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # adjust this to your build output directory
