# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - main

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '17'
          
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: |
          npm run build
          npm run publishsitemap
          touch docs/.nojekyll
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: docs
      - name: Deploy
        run: npm run deploy
        env:
          CI: true
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: docs
      - name: Deploy to GitHub Pages to prod
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
